[program:discord_bot]
command=/root/.venv/bin/python /app/discord_bot/bot.py
directory=/app/discord_bot
autostart=true
autorestart=unexpected
exitcodes=0
startretries=5
startsecs=10
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/supervisor/discord_bot.out.log
stderr_logfile=/var/log/supervisor/discord_bot.err.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
environment=PYTHONUNBUFFERED=\"1\"
